# Generated by Django 4.2.7 on 2025-08-24 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='TRY', max_length=3)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('md_status', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
